POST  http://localhost:8080/saveMember
Content-Type: application/json

{
  "name": "member1",
  "email": "juna1234@naver.com",
  "password": "1234"
}


### 상품 등록 1
POST http://localhost:8080/api/save/item
Content-Type: application/json

{
  "name": "item3",
  "description": "item3는 좋아요",
  "price": 10000,
  "quantity": 10
}

### 상품 등록 2
POST http://localhost:8080/api/save/item
Content-Type: application/json

{
  "name": "item4",
  "description": "item4는 별로에요",
  "price": 222222,
  "quantity": 222
}

### 상품 조회
GET http://localhost:8080/api/get/1


### 상품 수정
PUT http://localhost:8080/api/update/2
Content-Type: application/json

{
  "name": "item2",
  "description": "item2 description",
  "price": 200,
  "quantity": 10
}

### 상품 삭제
DELETE http://localhost:8080/api/delete/1

### 상품 전체 조회
GET http://localhost:8080/api/getList?page=1&size=10

### 상품 전체 조회
GET http://localhost:8080/api/getListByCond?name=&description=&price=200000&quantity=90

